version: '3'

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "25:25"
      - "80:80"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - LETSENCRYPT_EMAIL=admin@human-kenna-proklinik-d2822aa5.koyeb.app
      - LETSENCRYPT_HOST=mail.human-kenna-proklinik-d2822aa5.koyeb.app
      - VIRTUAL_HOST=mail.human-kenna-proklinik-d2822aa5.koyeb.app
    volumes:
      # - /etc/localtime:/app/etc/localtime:ro
      # - /mnt/poste:/da
